_target_: src.models.FM_module.FmModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: FM.model.FactorizationMachineModel
  field_dims: [192403,63001]
  embed_dim: 256
  