embedding_size: [64,128]
feat_embed_dim: [64,128]

n_layers: [1,2,3,4]
dropout: [0.3,0.5]
reg_weight: 0.01
cl_weight: 2.0

use_neg_sampling: False

hyper_parameters: ["n_layers", "dropout", "embedding_size", "feat_embed_dim"]