_target_: src.models.Multi_VAE_module.MultiVaeModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 10
  

net:
  _target_: Multi_VAE.model.MultiVAE
  p_dims: [256,1024,62845]
  
  
  